config/routes.rb
Raa::Application.routes.draw do
  get 'pages/:id.html' => 'pages#show', as: :page
  resources :links
  resources :menus
  resources :categories
  resources :posts
  resources :pages
  root :to => "home#index"
  devise_for :admin_users
end

app/models/menu.rb
class Menu
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :ord, type: Integer, default: ->{ Category.count + 1}
  field :url, type: String

  belongs_to :parent, class_name: 'Menu', inverse_of: :menus
  has_many :menus, inverse_of: :parent

  belongs_to :page, inverse_of: nil
  belongs_to :post, inverse_of: nil
  belongs_to :category, inverse_of: nil

  scope :root, ->{where(parent: nil)}
  default_scope ->{ asc [:ord, :created_at] }

  index({ ord: 1 }, {background: true })

  validates :name, presence: true, uniqueness: true
  validate :url_page_category_need_one

  def url_page_category_need_one
    errors.add(:url, :url_page_category_need_one) if url.blank? and page.blank? and category.blank? and post.blank?
  end

  def to_s
    name
  end
end

app/controllers/menus_controller.rb
class MenusController < InheritedResources::Base
  before_filter :authenticate_admin_user!
  defaults :resource_class => Menu, :collection_name => 'menus', :instance_name => 'menu'

  def create
    create!{new_menu_path}
  end

  def update
    update!{menus_path}
  end

  def permitted_params
    params.permit(menu: [:parent, :name, :ord, :url, :page, :category, :post])
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%#= f.input :parent, collection: Menu.all, prompt: '请选择父分类,不选择则为顶级分类' %>
    <%= f.input :name %>
    <%= f.input :ord %>
    <%= f.input :url %>
    <%= f.input :page, collection: Page.all, prompt: '请选择跳转到的页面' %>
    <%= f.input :post, collection: Post.all, prompt: '请选择跳转到的文章' %>
    <%= f.input :category, collection: Category.all, selected: :category, prompt: '请选择跳转到的分类' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ord</th>
      <th>url</th>
      <th>page</th>
      <th>post</th>
      <th>category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to menu.name, menu %></td>
        <td><%= menu.ord %></td>
        <td><%= menu.url %></td>
        <td><%= link_to menu.page, menu.page if menu.page %></td>
        <td><%= link_to menu.post, menu.post if menu.post %></td>
        <td><%= menu.category %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Ord:</strong>
  <%= @menu.ord %>
</p>

<p>
  <strong>Path:</strong>
  <%= @menu.path %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>