config/routes.rb
Raa::Application.routes.draw do
  get 'pages/:id.html' => 'pages#show', as: :page
  resources :links
  resources :menus
  resources :categories
  resources :posts
  resources :pages
  root :to => "home#index"
  devise_for :admin_users
end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Tree
  include Mongoid::Tree::Ordering

  field :name, type: String
  #field :path, type: String
  #field :ord, type: Integer, default: ->{ Category.count + 1}
  #belongs_to :parent, class_name: 'Category', inverse_of: :categories
  #has_many :categories, inverse_of: :parent
  #has_many :pages
  has_many :posts, class_name: 'Post', inverse_of: :category

  #belongs_to :path_page, class_name: 'Page', inverse_of: nil

  #accepts_nested_attributes_for :categories

  #scope :root, ->{where(parent: nil)}
  #default_scope ->{ asc [:depth, :position]  }

  validates :name, presence: true
  
  #index({ ord: 1 }, {background: true })

  def to_s
    #('-' * depth) + 
      name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  before_filter :authenticate_admin_user!, except: [:index, :show]
  #defaults resource_class: Category, collection_name: 'categories', instance_name: 'category'
  #
  def create
    create!{new_category_path}
  end

  def permitted_params
    params.permit(category: [:name, :parent, :position, :depth])
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :parent, collection: Category.all, prompt: '请选择父分类,不选择则为顶级分类', label_method: :to_s %>
    <%#= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>