config/routes.rb
Raa::Application.routes.draw do
  get 'pages/:id.html' => 'pages#show', as: :page
  resources :links
  resources :menus
  resources :categories
  resources :posts
  resources :pages
  root :to => "home#index"
  devise_for :admin_users
end

app/views/layouts/_footer.html.erb
<div id="links">
  <div class="container">
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="">关于</h4>

        <ul class="">
          <li class="item-102"><a href="/pages/53180e0d7261615603020000.html">关于我们</a></li><li class="item-162"><a href="#">版权声明</a></li><li class="item-163"><a href="#">免责声明</a></li><li class="item-164"><a href="#">网站地图</a></li></ul>

      </div>


    </div>
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="">业务</h4>

        <ul class="">
          <li class="item-178"><a href="#">柳州网站建设</a></li><li class="item-179"><a href="#">柳州网站设计</a></li><li class="item-180"><a class="nofollow" href="#">柳州主机租赁</a></li></ul>

      </div>


    </div>
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="">联系</h4>

        <ul class="">
          <li class="item-182"><a href="/pages/53180e0d7261615603020000.html">联系我们</a></li><li class="item-248"><a href="http://wpa.qq.com/msgrd?v=3&amp;uin=152227999&amp;site=qq&amp;menu=yes">在线咨询</a></li></ul>

      </div>


    </div>
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="">支持</h4>

        <ul class="">
          <li class="item-185"><a href="#">网站案例</a></li><li class="item-183"><a href="#">网站建设知识</a></li><li class="item-251"><a href="#" target="_blank">Bootstrap</a></li></ul>

      </div>


    </div>
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="">案例</h4>

        <ul class="">
          <li class="item-186"><a href="#">科技网站</a></li><li class="item-187"><a href="#">数码网站</a></li><li class="item-252"><a href="#">Bootstrap网站</a></li><li class="item-188"><a href="#">电器网站</a></li><li class="item-189"><a href="#">餐饮网站</a></li></ul>

      </div>


    </div>
    <div class="links span2 ">
      <div class="moduletable">

        <h4 class="wx-stamp">微信关注</h4>

        <ul class="">
          <li class="item-237 divider"><span class="separator">
              <!--
              <img src="/ui/img/weixin.png" alt="现实与应用微信">
              -->
            </span>
        </li></ul>

      </div>


    </div>
  </div>
</div>
<div id="copyright">
  <div class="container">
    <ul class="list-inline">
      <%= render "layouts/friend_links" %>
    </ul>
    <div class="copyright"> Copyright © 2013 现实与应用REALITYANDAPP.COM - 用心创造每一站, All Rights Reserved. <a href="#">柳州网站建设</a>, <a href="#">柳州网站设计</a>, <a href="#">柳州网站制作</a>  
      <!--<a href="http://tongji.baidu.com/hm-web/welcome/ico?s=994c57aedfc1779e135da9839e946ed9" class="icon-baidu" target="_blank" rel="nofollow"><div class="baidu-icon"></div></a>-->
    </div>
  </div>
</div>

app/views/layouts/_friend_links.html.erb
<% Link.all.each do |link| %>
  <li class="item-212"><%= link_to link.name, link.url, target: '_blank', rel: link.is_follow ? '' : 'external nofollow' %></li>  
<% end -%>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="container navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to '现实与应用', root_path, class: 'navbar-brand' %>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% @menus = Menu.all %>
<% @menus.each do |menu| %>
  <li>
    <% if !menu.url.blank? %>
      <%= link_to menu.name, menu.url %>
    <% elsif !menu.page.blank? %>
      <%= link_to menu.name, menu.page %>
    <% elsif !menu.post.blank? %>
      <%= link_to menu.name, menu.post %>
    <% elsif !menu.category.blank? %>
      <%= link_to menu.name, category_path(menu.category) %>
    <% end -%>
  </li>
<% end -%>
<!--
<li><%= link_to '网站建设','/' %></li>
<li><%= link_to '网站设计','/' %></li>
<li><%= link_to '应用制作','/' %></li>
<li><%= link_to '案例演示','/' %></li>
<li><%= link_to '主机租赁','/' %></li>
<li><%= link_to '联系我们','/' %></li>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= display_meta_tags default_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target="main"> 
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>